### ISSUE TITLE
Gazebo plugin does not print debugs

### ISSUE THREAD

**Issue by bach05** [BruceChanJianLe/gazebo-plugin-autonomous-actor#1]
I'm trying to use your plugin in the simple_office_with_people.world of [PAL Robotics](http://wiki.ros.org/Robots/TIAGo/Tutorials/motions/key_teleop) for TIAGo simulation. 

The actor after some seconds of motions gete stuck and starts turning back and forth between 2 opposite angles. I would like to debug the code, but I'm not able to see any print. I followed your instructions and I pasted the snippet in the simple_office_with_people.world file. Then I launch with:
`roslaunch tiago_gazebo tiago_gazebo.launch public_sim:=true robot:=titanium world:=simple_office_with_people`

Being able to debug in different world would be useful for developing. Thank a lot for your help in advance.

**Comment by BruceChanJianLe** [comment]
Hi there, thanks for your questions on the plugin.

To use the debug message, you will first need to load the correct plugin, which is AutonomousActorPluginDebug.so file.

If you are still unable to see any debug output, you may want to set verbose to true. Here a link where you can have some idea about what I am referring to.

By the way, I would like to add that this plugin is still under development, I have not got any time to work on it for awhile.

Let me know if you have any other questions.

**Comment by BruceChanJianLe** [comment]
If you have no other questions, I shall close the issue. Do open a new one if you have any other further questions.
