### ISSUE TITLE
Hi，Where is the package gazebo_person_detection

### ISSUE THREAD

**Issue by NJUSTDragon** [BruceChanJianLe/gazebo-plugin-autonomous-actor#2]
As the title,  I can not find the package

**Comment by BruceChanJianLe** [comment]
Hi there, I am unsure why this question is posted here. Please kindly check the package.xml properly.

This package does not offer gazebo_person_detection, do point out where you find this package in the repo.

**Comment by NJUSTDragon** [comment]
Thank you for your reply. It's my fault
